version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=ecb
      - POSTGRES_USER=ecb
      - POSTGRES_DB=ecb-currency
    expose:
      - '5432'
