server:
  port: 9000
springdoc:
  swagger-ui:
    path: swagger-ui.html
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecb-currency
    username: ecb
    password: ecb
    driver-class-name: org.postgresql.Driver
    platform: postgres
  jpa:
    properties:
      hibernate:
        order_inserts: true
        jdbc:
          batch_size: 30
    generate-ddl: false
    hibernate:
      ddl-auto: create